project:
  type: website
  output-dir: docs

website:
  title: "LaborLytics Project Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Data
        href: data.qmd
      - text: Analysis and Graphs
        href: Analysis and Graphs.qmd
      - text: Labor Market Health Check
        href: health-check.qmd
      - text: Guess the Year?
        href: guess-test.qmd




            
    tools:
      - icon: github
        href: https://github.com/emu-hacettepe-analytics/emu430-fall2024-team-laborlytics

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Spring 2026" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: simplex
    css: styles.css


editor: visual

